IvanCybercom/Hackademy-IV-frontend

README.md
=> GIT repo changes

src/app/admin/admin-routing.module.ts, src/app/app-routing.module.ts
=> Hac admin component routing

src/assets/mockdata/organizations.json, src/assets/mockdata/projects.json
I created two mock-up data files. "organizations.json" and "projects.json" which consist of the requested properties in the "UserStories Overall Design.docx" file. It's no definitive but it's a start. Changes are welcome to come.
=> organizations.json and projects.json (partially) mock data

src/app/admin/admin.module.ts
Need to import the shared module in admin
=> Imported the shared module to Admin

src/app/admin/interface/contact.ts, src/app/admin/interface/organization.ts
Created neccesary interfaces that are going to be used throughout the project, especially in Admin epic. Those are : 
1. IOrganization.
2. IContact (which is part of IOrganization also).
=> interfaces created, organization + contact

src/app/projects/projectInterface.ts, src/assets/mockdata/projects.json
json was created and the interface for projects
=> The project interface and project data are added to the project

src/app/admin/admin-toolbar/admin-toolbar.component.html, src/app/admin/admin-toolbar/admin-toolbar.component.spec.ts, src/app/admin/admin-toolbar/admin-toolbar.component.ts, src/app/admin/admin.component.html, src/app/admin/admin.module.ts
A new admin toolbar component, and a router outlet in the admin component
=> Hac 002 001/admin toolbar component

src/app/shared/shared.module.ts
Please review the change. I think we all agreed/agreeing on adding another shared module to the shared.module.ts file.
**NOTE**: Review asap because we would be able to merge it to origin/development branch and continue with our tasks.
=> Shared Module Update Request!

src/app/admin/admin-toolbar/admin-toolbar.component.spec.ts, src/app/admin/admin.component.spec.ts
Added a few tests to the admin toolbar and to the admin component
=> Merge new tests 

src/app/admin/services/data.service.spec.ts, src/app/admin/services/data.service.ts
Just as the title says not much to add.
=> Data Service reworked and updated to be easy readable and implementable

src/app/projects/project.service.spec.ts, src/app/projects/projects.component.spec.ts
The basic test has been added to project service.
=> basic test added

src/app/admin/organization-list/organization-list.component.html, src/app/admin/organization-list/organization-list.component.scss, src/app/admin/organization-list/organization-list.component.spec.ts, src/app/admin/organization-list/organization-list.component.ts
**Achieved**:
- Table with rows and cells that grab mock data
- Clean and readable code.
Please review my code and suggest for merge.
=> Admin Organizations List Created

src/app/admin/admin-routing.module.ts, src/app/admin/admin.module.ts, src/app/admin/organization-page/organization-page.component.html, src/app/admin/organization-page/organization-page.component.spec.ts, src/app/admin/organization-page/organization-page.component.ts
=> Show the organization page

src/app/app.component.html, src/app/projects/project-list/project-list.component.html, src/app/shared/navbar.component.html, src/app/shared/navbar.component.scss, src/app/shared/navbar.component.spec.ts, src/app/shared/navbar.component.ts, src/app/shared/shared.module.ts
Nav bar component has been created and can be used by its selector. Note, it needed to be added to shared module so it is necessary to remain there to be deployed later.
=> navbar component

src/app/app.component.spec.ts, src/app/projects/project-list/project-list.component.spec.ts, src/app/shared/navbar.component.spec.ts
fixing tests failures in the train by al and Yaseen
=> fixing tests in the train by al and Yaseen

src/app/app-routing.module.ts, src/app/projects/project-list/project-list.component.html, src/app/projects/project-list/project-list.component.scss
fixing the routing problem to the project list also in the train by Yaseen and Al
=> Hac 13 007/project list update

src/app/admin/admin-routing.module.ts, src/app/admin/admin.module.ts
New Component to get project lists.
=> Created Projects List Component and connected to Admin module + Routing

src/app/app-routing.module.ts, src/app/app.component.html, src/app/projects/project-list/project-list.component.ts, src/app/projects/projects-routing.module.ts, src/app/projects/projects.component.html, src/app/projects/projects.component.spec.ts, src/app/projects/projects.component.ts
navbar is now only shown in the project component, not in the admin!
=> Hac 13 001/navbar component  to development

src/app/admin/admin-routing.module.ts, src/app/admin/admin.module.ts, src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.spec.ts, src/app/admin/project-form/project-form.component.ts
Boiler plate files + admin route path added. Will provide updated code during the day. Stay tuned!!!
=> Created Admin Project Form Component and linked in Admin Router Module

src/app/projects/project.interface.ts, src/assets/mockdata/projects.json
I have added the organizationId to the project.json and project.interface.ts
=> Hac 13 004/project json adding

src/app/projects/project-list/project-list.component.html, src/app/projects/project-list/project-list.component.scss, src/app/shared/navbar.component.html, src/app/shared/navbar.component.scss, src/app/shared/shared.module.ts
improving the overall responsiveness and rebuilding the nav bar.
=> Hac 54 008/ui improvments

src/app/projects/projects.module.ts, src/app/shared/shared.module.ts
=> agmCoreModule is now imported and exported from shared

src/app/app-routing.module.ts, src/app/projects/projects-routing.module.ts
Geo location has been improved and the navbar has been added.
=> navbar is now added to the geolocation as well

src/app/projects/project-list/project-list.component.html, src/app/projects/project-list/project-list.component.ts, src/app/shared/donate-button/donate-button.component.html, src/app/shared/donate-button/donate-button.component.ts, src/app/shared/progressbar.component.ts
The progressbar is now dynamically updated by donating.
=> Hac 54 004/dynamic progressbar

src/app/admin/admin.module.ts, src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.scss, src/app/admin/project-form/project-form.component.spec.ts, src/app/admin/project-form/project-form.component.ts, src/app/admin/project-form/project-form.constants.ts, src/assets/mockdata/organizations.json
Added new validation rules. Peer to peer work with Ahmed.
Fixed testings and added missing inputs.
=> Tested and fixed merging conflicts

src/app/projects/project-list/project-list.component.ts, src/app/projects/project.service.ts
The project service now has a function to return list of favorite projects give the projects' id.
=> favorit projects can be returned from project service

src/app/projects/project-list/project-list.component.html, src/app/projects/project-list/project-list.component.scss, src/app/projects/project-list/project-list.component.ts, src/app/shared/donate-button/donate-button.component.html, src/app/shared/donate-button/donate-button.component.scss, src/app/shared/donate-button/donate-button.component.ts, src/app/shared/progressbar.component.html, src/app/shared/progressbar.component.scss
Styling the progress bar and the donate button
=> Hac 54 003/donate button update

src/app/projects/project.service.ts
A function, getSelectedProject, has been added to the project service. It takes one argument which is the index of project to be retrieved.
=> service for the selected project

src/app/projects/project.service.ts, src/assets/mockdata/activities.json
the project service had a bug returning one event and now it is fixed. some bugs are fixed in the activities.json file as well.
=> projectService is fixed

src/app/admin/interface/organization.ts, src/app/admin/interface/project.ts
An update on interfaces. Created two new interfaces on the same files but didnt change the previous ones, instead they are deprecated therefore it won't crash the entire code.
=> Created new interfaces within the same files but deprecated old ones

src/app/admin/admin.module.ts, src/app/admin/organization-list/organization-list.component.html, src/app/admin/organization-list/organization-list.component.scss, src/app/admin/organization-list/organization-list.component.ts, src/app/admin/project-list/project-list.component.html, src/app/admin/project-list/project-list.component.scss, src/app/admin/project-list/project-list.component.ts, src/app/admin/sidebar/sidebar.component.ts
added Material table on project list and organization list and changed the data load for the respective table to be compatible with material table.
=> Update tables  on project and organization list with material table 

karma.conf.js, src/app/admin/organization-form/organization-form.component.spec.ts, src/app/admin/organization-list/organization-list.component.spec.ts, src/app/admin/project-list/project-list.component.spec.ts, src/app/admin/reports/closed-projects/closed-projects.component.spec.ts, src/app/shared/shared.module.ts
Previous related branch (closed): #143
=> Sprint 3 Tests, Shared Module imports/exports and Closed Projects Component

src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.spec.ts
other tests can follow the same logic
=> First tests for the project form

src/app/shared/progressbar.component.spec.ts
this is isolated test for progress-bar
=> added IT for progressbar

src/app/admin/interface/organization.ts, src/app/admin/interface/project.ts, src/app/projects/project.interface.ts
Adjusted missing properties on both Donor/Admin interfaces and reordered them to better reflect their respective structure.
**Related issue:**
[Admin/Donor Interfaces unmatching](https://github.com/IvanCybercom/Hackademy-IV-frontend/issues/177)
=> App Maintaining - Interface changes

src/app/admin/services/nano-validators.ts
this will be used in solving validation errors in forms
=> A nano validation service.

src/app/admin/interface/organization.ts, src/app/admin/interface/project.ts, src/app/admin/organization-form/organization-form.component.html, src/app/admin/organization-form/organization-form.component.ts, src/app/admin/organization-list/organization-list.component.html, src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.ts, src/app/admin/project-list/project-list.component.html, src/app/admin/services/nano-validators.ts, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/donor/donor-overview/donor-overview.component.ts, src/app/donor/donor-services/donor-register.service.spec.ts, src/app/donor/donor-services/donor-register.service.ts, src/app/projects/project-list/project-list.component.html, src/app/projects/project-list/project-list.component.scss, src/app/projects/project-list/project-list.component.ts, src/app/projects/project.interface.ts, src/app/projects/project.service.ts, src/app/service/local-storage.service.spec.ts, src/app/service/local-storage.service.ts
Local storage service now is ready to use and it is already been used in the saved project.
=> Hac 54 007/local storage

src/app/shared/_progressbar.component-theme.scss, src/app/shared/progressbar.component.scss, src/app/shared/progressbar.component.ts
The progressbar component is taking the color from the nano theme.
=> Progressbar use color from nano theme

src/app/shared/_navbar.component-theme.scss, src/app/shared/navbar.component.scss, src/app/shared/navbar.component.ts
The background of the navbar now takes the color from nano-theme
=> Hac 13 001/navbar component

src/app/geolocation/geolocation.component.html, src/app/geolocation/geolocation.component.scss, src/app/geolocation/geolocation.component.ts, src/app/projects/project-list/project-list.component.ts, src/app/projects/projects.module.ts, src/app/service/geolocation.service.ts, src/app/shared/shared.module.ts, src/assets/mockdata/projects.json
The current and default location tabs are now working... the projects are based on the geocode... and the markers for the projects are now set to their centers.
=> geolocation service

src/app/geolocation/geolocation.component.html, src/app/geolocation/geolocation.component.ts
The map will recenter to the current location in case it is zoomed or panned without changing the marker place. the same goes for default location.
=> Hac ehsan geo zoom

src/app/admin/organization-form/organization-form.component.html, src/app/admin/organization-form/organization-form.component.scss, src/app/admin/organization-form/organization-form.component.ts, src/app/interfaces/organization.ts, src/app/interfaces/project.ts, src/app/shared/services/data.service.ts
Saving the new organization data input to the database.
=> Hac 116 001/storing organizations data

src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.ts, src/app/service/geolocation.service.ts
Saving the Data of a project to the database
=> Hac 117 001/storing project data

handover-plan.md, src/app/admin/activity-form/activity-form.component.html, src/app/admin/activity-form/activity-form.component.ts, src/app/admin/admin.module.ts, src/app/admin/dashboard/dashboard.component.html, src/app/admin/dashboard/dashboard.component.scss, src/app/admin/dashboard/dashboard.component.ts, src/app/admin/dashboard/keys.pipe.spec.ts, src/app/admin/dashboard/keys.pipe.ts, src/app/admin/organization-form/organization-form.component.html, src/app/admin/organization-form/organization-form.component.scss, src/app/admin/organization-form/organization-form.component.ts, src/app/admin/project-form/project-form.component.html, src/app/admin/project-form/project-form.component.scss, src/app/admin/project-page/project-page.component.html, src/app/admin/reports/closed-projects/closed-projects.component.html, src/app/geolocation/geolocation.component.ts, src/app/interfaces/activity.ts, src/app/shared/services/data.service.ts, src/environments/environment.ts
Create a new Event for a specifik project
=> Hac 118 001/storing activity data

src/app/shared/donate-button/donate-button.component.html, src/app/shared/donate-button/donate-button.component.scss, src/app/shared/donate-button/donate-button.component.ts
Open Swish app when click on donate
=> Hac 98 001/swish

src/app/admin/reports/closed-projects/closed-projects.component.html, src/app/admin/reports/closed-projects/closed-projects.component.scss, src/app/admin/reports/closed-projects/closed-projects.component.ts, src/app/admin/reports/reports.module.ts
=> Added Reset Button in Closed Projects + fixed Filtering
